// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 9/5/2026, 10:58:59 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
import cfg3 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/Users/a202/Downloads/optima-nuxt-website/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/a202/Downloads/optima-nuxt-website/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/a202/Downloads/optima-nuxt-website/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/a202/Downloads/optima-nuxt-website/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/a202/Downloads/optima-nuxt-website/plugins/**/*.{js,ts,mjs}","/Users/a202/Downloads/optima-nuxt-website/composables/**/*.{js,ts,mjs}","/Users/a202/Downloads/optima-nuxt-website/utils/**/*.{js,ts,mjs}","/Users/a202/Downloads/optima-nuxt-website/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/a202/Downloads/optima-nuxt-website/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/a202/Downloads/optima-nuxt-website/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/a202/Downloads/optima-nuxt-website/app.config.{js,ts,mjs}"]}},
{},
cfg2,
cfg3
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;